In [1]:
from data_generator import DataGenerator 
import preprocessing as pre
import analytics as anl
from reporting import Report

In [2]:
satis = DataGenerator(100,42)

In [3]:
df = satis.generate_data()

In [4]:
pre.missing_values(df)

--- Veri Genel Bilgisi ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Müşteri ID    100 non-null    int32
 1   Ürün          100 non-null    object
 2   Satış Tutarı  95 non-null     float64
 3   Şehir         95 non-null     object
 4   Ay            100 non-null    object
dtypes: float64(1), int32(1), object(3)
memory usage: 3.6+ KB

--- İstatistiksel Özet ve Eksik Veri Sayısı ---

(       Müşteri ID  Satış Tutarı
 count   100.00000  9.500000e+01
 mean   5823.67000  4.739963e+04
 std    2645.21029  2.303694e+05
 min    1064.00000  3.833160e+03
 25%    3601.00000  9.894920e+03
 50%    6267.00000  1.552071e+04
 75%    8126.25000  3.632131e+04
 max    9996.00000  2.263920e+06,
 Müşteri ID      0
 Ürün            0
 Satış Tutarı    5
 Şehir           5
 Ay              0
 dtype: int64)

In [5]:
df_filled = pre.fill_missing_values(df)

In [6]:
df_final = pre.add_features(df_filled)

In [7]:
city = anl.get_city_performance(df_final)

In [8]:
city_perf = anl.calculate_performance_score(city,"Toplam Satış")

In [15]:
city_perf

        Şehir  Toplam Satış  Maksimum Satış  Minimum Satış  Performans Skoru
5       İzmir    2656340.40      2263920.00        9889.62            100.00
4    İstanbul     880324.26        47231.69        3833.16             31.13
0      Ankara     412179.26        44534.93        3851.08             12.97
1     Antalya     310650.03        47063.44        3954.16              9.04
3       Bursa     243470.75        44899.72        3895.29              6.43
2  Bilinmeyen      77603.55        15520.71       15520.71              0.00

In [9]:
product_perf = anl.get_product_performance(df_final)

In [16]:
product_perf

       Ürün  Toplam Satış  Satış Adedi
0  Kulaklık      79619.65           17
1    Laptop    3180353.00           22
2   Monitör     231178.89           22
3    Tablet     211366.66           14
4   Telefon     878050.05           25

In [10]:
monthly_perf = anl.get_monthly_performance(df_final)

In [17]:
monthly_perf

         Ay  Toplam Satış  Ortalama Satış  Aylık Değişim(%)
0    Aralık     143561.86    20508.837143               NaN
1   Ağustos      65814.59    16453.647500            -54.16
2      Ekim     193947.22    21549.691111            194.69
3     Eylül      63779.32    10629.886667            -67.12
4   Haziran     228404.90    25378.322222            258.12
5     Kasım    2663868.82   133193.441000           1066.29
6      Mart     547642.68    32214.275294            -79.44
7     Mayıs      60886.58    30443.290000            -88.88
8     Nisan     144844.07    20692.010000            137.89
9      Ocak     211317.10    21131.710000             45.89
10   Temmuz      66447.82    22149.273333            -68.56
11    Şubat     190053.29    31675.548333            186.02

In [11]:
best_sellers = anl.get_monthly_best_seller(df_final)

In [18]:
best_sellers

         Ay     Ürün  Satış Tutarı
19    Kasım   Laptop    2413831.34
27     Mart  Telefon     281461.57
9      Ekim  Telefon     140193.80
40    Şubat   Laptop     134813.13
37     Ocak  Telefon     106994.07
17  Haziran  Telefon     102727.39
30    Nisan   Laptop      90367.67
0    Aralık   Laptop      88426.50
4   Ağustos   Laptop      47231.69
28    Mayıs   Laptop      45365.87
39   Temmuz  Telefon      36270.98
12    Eylül   Tablet      30229.57

In [12]:
df_dict = {
    "Şehir Analizi":   city_perf,
    "Ürün Analizi":    product_perf,
    "Aylık Özet":      monthly_perf,
    "En Çok Satanlar": best_sellers
}

In [13]:
report = Report(df_dict)

In [19]:
toplam_satis = df_final["Satış Tutarı"].sum()
en_karli_sehir = city_perf.sort_values("Toplam Satış", ascending=False).iloc[0]["Şehir"]
en_iyi_ay = monthly_perf.sort_values("Toplam Satış", ascending=False).iloc[0]["Ay"]

In [20]:
print(f"Toplam Satış     : {toplam_satis:,.0f} TL")
print(f"En Kârlı Şehir   : {en_karli_sehir}")
print(f"En İyi Ay        : {en_iyi_ay}")

Toplam Satış     : 4,580,568 TL
En Kârlı Şehir   : İzmir
En İyi Ay        : Kasım

In [14]:
report.toExcel("Capstone_Final_Satis_Raporu.xlsx")

Rapor 'Capstone_Final_Satis_Raporu.xlsx' adıyla başarıyla oluşturuldu.